name: spend_wise
description: "Flutter application for managing expenses and income."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  intl: ^0.20.2
  image_picker: ^1.2.1
  google_mlkit_text_recognition: ^0.15.0
  http: ^1.6.0
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  cloud_firestore: ^5.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true